from pathlib import Path
from datetime import datetime, timezone
from OPERATORS.engine import CognitiveOperator
import entity_markdown as em


class Operator(CognitiveOperator):
    def __init__(self, event_bus=None):
        self.event_bus = event_bus

    def inputs(self):
        return ['learning_path']

    def validate(self, learning_path, **kwargs):
        sections = em.load_entity(learning_path)
        return bool(sections.get('Learning', '').strip())

    def execute(self, learning_path, **kwargs):
        sections = em.load_entity(learning_path)
        source_path = Path(learning_path)
        memory_id = 'memory-' + source_path.stem
        today = datetime.now(timezone.utc).strftime('%Y-%m-%d')

        new_sections = {
            'Identity': memory_id,
            'Ownership': 'Owned by the Memory Organ, per QENKI_MIND_ORGANS_v1.md. Generated by the Learning -> Memory cognitive operator.',
            'Canonical Basis': str(source_path),
            'Context': 'Consolidated from Learning entity ' + str(source_path) + ' for long-term reuse in reasoning.',
            'Hypotheses': sections.get('Hypotheses', 'None inherited.'),
            'Predictions': sections.get('Predictions', 'None inherited.'),
            'Consequences': sections.get('Consequences', 'None inherited.'),
            'Learning': sections.get('Learning', 'None inherited.'),
            'Links': '- ' + str(source_path) + '\n- MEMORY/README.md',
            'Current State': 'Consolidated',
            'Change History': '- ' + today + ': Initialized by LearningToMemory operator from ' + str(source_path) + '.',
            'Last Updated': today,
        }

        target_path = Path('MEMORY') / (memory_id + '.md')
        return {'sections': new_sections, 'path': target_path}

    def persist(self, result, **kwargs):
        path = Path(result['path'])
        path.parent.mkdir(parents=True, exist_ok=True)
        em.save_entity(path, result['sections'])
        return path

    def emit_events(self, result, **kwargs):
        if not self.event_bus:
            return []
        event = self.event_bus.emit(
            'OperatorExecuted',
            self.__class__.__name__,
            str(result['path']),
        )
        return [event]
