from pathlib import Path
from datetime import datetime, timezone
from OPERATORS.engine import CognitiveOperator
import entity_markdown as em
import prediction_representation as pr


class NoResolvedPredictionsError(Exception):
    pass


class Operator(CognitiveOperator):
    def __init__(self, event_bus=None):
        self.event_bus = event_bus

    def inputs(self):
        return ['expression_path']

    def validate(self, expression_path, **kwargs):
        sections = em.load_entity(expression_path)
        predictions = pr.parse_predictions(sections['Predictions'])
        pr.validate_predictions(predictions)
        if not pr.has_resolved_predictions(predictions):
            raise NoResolvedPredictionsError(
                'No resolved (confirmed/disconfirmed) predictions found in ' + str(expression_path)
            )
        return True

    def execute(self, expression_path, **kwargs):
        sections = em.load_entity(expression_path)
        predictions = pr.parse_predictions(sections['Predictions'])
        resolved = pr.resolved_predictions(predictions)

        source_path = Path(expression_path)
        learning_id = 'learning-' + source_path.stem

        confirmed = [p for p in resolved if p['state'] == 'confirmed']
        disconfirmed = [p for p in resolved if p['state'] == 'disconfirmed']

        learning_lines = []
        for p in confirmed:
            learning_lines.append('- [' + p['id'] + '] Confirmed: ' + p['statement'])
        for p in disconfirmed:
            learning_lines.append('- [' + p['id'] + '] Disconfirmed: ' + p['statement'])

        today = datetime.now(timezone.utc).strftime('%Y-%m-%d')

        new_sections = {
            'Identity': learning_id,
            'Ownership': 'Owned by the Learning & Reflection Organ, per QENKI_MIND_ORGANS_v1.md. Generated by the Consequence -> Learning cognitive operator.',
            'Canonical Basis': str(source_path),
            'Context': 'Derived from resolved Predictions in ' + str(source_path) + '. Records confirmed and disconfirmed outcomes for calibration purposes.',
            'Hypotheses': sections.get('Hypotheses', 'None inherited.'),
            'Predictions': '\n'.join(learning_lines) if learning_lines else 'None resolved.',
            'Consequences': sections.get('Consequences', 'None inherited.'),
            'Learning': '\n'.join(learning_lines) if learning_lines else 'No resolved predictions to learn from yet.',
            'Links': '- ' + str(source_path) + '\n- LEARNING/README.md',
            'Current State': 'Recorded',
            'Change History': '- ' + today + ': Initialized by ConsequenceToLearning operator from ' + str(source_path) + '.',
            'Last Updated': today,
        }

        target_path = Path('LEARNING') / (learning_id + '.md')
        return {'sections': new_sections, 'path': target_path, 'resolved_count': len(resolved)}

    def persist(self, result, **kwargs):
        path = Path(result['path'])
        path.parent.mkdir(parents=True, exist_ok=True)
        em.save_entity(path, result['sections'])
        return path

    def emit_events(self, result, **kwargs):
        if not self.event_bus:
            return []
        event = self.event_bus.emit(
            'OperatorExecuted',
            self.__class__.__name__,
            str(result['path']),
            payload={'resolved_count': result['resolved_count']},
        )
        return [event]
