from pathlib import Path
from datetime import datetime, timezone
from OPERATORS.engine import CognitiveOperator
from REASONERS.evidence_ranker import EvidenceRanker
from REASONERS.hypothesis_generator import HypothesisGenerator
from REASONERS.confidence_estimator import ConfidenceEstimator
from REASONERS.decision_selector import DecisionSelector
from collections import OrderedDict
import entity_markdown as em

BASE = Path(__file__).resolve().parents[2]

MINIMAL_DECISION_STRUCTURE = [
    "Identity", "Ownership", "Canonical Basis", "Context", "Hypotheses",
    "Predictions", "Consequences", "Learning", "Links", "Current State",
    "Change History", "Last Updated",
]


class Operator(CognitiveOperator):
    def __init__(self, event_bus=None):
        self.event_bus = event_bus
        self.last_artifacts = []
        self.last_events = []

    def inputs(self):
        return ["opportunity_entity", "world_state", "objectives", "memory"]

    def validate(self, entity, session=None, **kwargs):
        if not entity:
            raise ValueError("Opportunity entity is required")
        return True

    def execute(self, entity, session=None, **kwargs):
        world_state = kwargs.get("world_state") or (
            session.world_state_snapshot if session else None
        )
        objectives = kwargs.get("objectives") or (
            session.objectives_snapshot if session else None
        )
        memory = kwargs.get("memory") or (session.memory_loaded if session else [])

        evidence_set = EvidenceRanker().run(entity, world_state, objectives, memory)
        hypotheses = HypothesisGenerator().run(entity, evidence_set)
        confidence = ConfidenceEstimator().run(evidence_set)
        selection = DecisionSelector().run(entity, confidence)

        # Canonical decision identity: simple string, compatible with
        # DecisionToExpression which calls .replace("decision-", "expression-", 1).
        if "OPP" in str(entity):
            decision_id = str(entity).replace("OPP", "DEC")
        else:
            stem = Path(str(entity)).stem if Path(str(entity)).suffix else str(entity)
            decision_id = f"decision-{stem}"

        return {
            "opportunity_id": entity,
            "decision_id": decision_id,
            "world_state": world_state,
            "objectives": objectives,
            "memory": memory,
            "evidence_set": evidence_set,
            "hypotheses": hypotheses,
            "confidence": confidence,
            "selected": selection["selected"],
            "rationale": selection["rationale"],
            "predictions": selection["predictions"],
            "session_id": getattr(session, "session_id", None),
        }

    def persist(self, result, session=None, **kwargs):
        ts = datetime.now(timezone.utc).date().isoformat()
        self.last_artifacts = []

        evidence_dir = BASE / "EVIDENCE"
        decisions_dir = BASE / "DECISIONS"
        evidence_dir.mkdir(exist_ok=True)
        decisions_dir.mkdir(exist_ok=True)

        # --- Evidence entity ---
        evidence_path = evidence_dir / f"evidence_set_for_{result['decision_id']}.md"
        ev_sections = OrderedDict()
        ev_sections["__title__"] = f"Evidence Set for {result['decision_id']}"
        ev_sections["Identity"] = f"evset-{result['decision_id']}"
        ev_sections["Ownership"] = (
            "Owned by the Decision Organ, per QENKI_MIND_ORGANS_v1.md. "
            "Generated by the Opportunity → Decision cognitive operator."
        )
        ev_sections["Canonical Basis"] = f"Opportunity: {result['opportunity_id']}"
        ev_sections["Evidence Items"] = em.build_bullet_section([
            f"{item['evidence_id']} | {item['source']} | weight={item['weight']:.2f} | {item['summary']}"
            for item in result["evidence_set"]
        ])
        ev_sections["Supporting World State"] = em.build_bullet_section(
            [result["world_state"] or "none"]
        )
        ev_sections["Supporting Objectives"] = em.build_bullet_section(
            [result["objectives"] or "none"]
        )
        ev_sections["Supporting Memory"] = em.build_bullet_section(
            result["memory"] if result["memory"] else ["none"]
        )
        ev_sections["Generated Hypotheses"] = em.build_bullet_section(result["hypotheses"])
        ev_sections["Confidence Estimate"] = f"{result['confidence']:.2f}"
        ev_sections["Last Updated"] = ts

        em.save_entity(evidence_path, ev_sections)
        self.last_artifacts.append(evidence_path)

        # --- Decision entity (only when selected) ---
        if result["selected"]:
            decision_path = decisions_dir / f"{result['decision_id']}.md"

            dec_sections = OrderedDict()
            dec_sections["__title__"] = f"Decision: {result['decision_id']}"

            # Identity: canonical simple string, compatible with DecisionToExpression.
            dec_sections["Identity"] = result["decision_id"]

            dec_sections["Ownership"] = (
                "Owned by the Decision Organ, per QENKI_MIND_ORGANS_v1.md. "
                "Generated by the Opportunity → Decision cognitive operator."
            )
            dec_sections["Canonical Basis"] = (
                f"Opportunity: {result['opportunity_id']}"
            )
            dec_sections["Context"] = em.build_bullet_section([
                f"World State: {result['world_state'] or 'none'}",
                f"Objectives: {result['objectives'] or 'none'}",
                f"Evidence Set: {evidence_path.name}",
                f"Session: {result['session_id'] or 'none'}",
            ])
            dec_sections["Hypotheses"] = em.build_bullet_section(result["hypotheses"])
            dec_sections["Predictions"] = em.build_bullet_section(
                result["predictions"] if result["predictions"] else ["none"]
            )
            dec_sections["Consequences"] = "None at time of decision."
            dec_sections["Learning"] = "None inherited at time of decision."
            dec_sections["Links"] = em.build_bullet_section(
                [
                    f"Opportunity: {result['opportunity_id']}",
                    f"Evidence: {evidence_path.name}",
                ]
                + [f"Memory: {m}" for m in result["memory"]]
            )
            dec_sections["Current State"] = "Selected"
            dec_sections["Change History"] = em.build_bullet_section([
                f"{ts}: Initialized by Opportunity → Decision operator."
            ])
            dec_sections["Last Updated"] = ts

            em.validate_entity_structure(dec_sections, MINIMAL_DECISION_STRUCTURE)
            em.save_entity(decision_path, dec_sections)
            self.last_artifacts.append(decision_path)
            return decision_path

        return evidence_path

    def emit_events(self, result, session=None, **kwargs):
        self.last_events = []
        if not self.event_bus:
            return []
        if result["selected"]:
            self.last_events.append(self.event_bus.emit(
                event_type="DecisionCreated",
                operator="OpportunityToDecision",
                source_entity=result["opportunity_id"],
                target_entity=result["decision_id"],
                payload={
                    "confidence": result["confidence"],
                    "session_id": result["session_id"],
                },
            ))
        else:
            self.last_events.append(self.event_bus.emit(
                event_type="DecisionRejected",
                operator="OpportunityToDecision",
                source_entity=result["opportunity_id"],
                target_entity=None,
                payload={
                    "confidence": result["confidence"],
                    "session_id": result["session_id"],
                },
            ))
        return self.last_events