from pathlib import Path
from datetime import datetime, timezone
from OPERATORS.engine import CognitiveOperator
from REASONERS.evidence_ranker import EvidenceRanker
from REASONERS.hypothesis_generator import HypothesisGenerator
from REASONERS.confidence_estimator import ConfidenceEstimator
from REASONERS.decision_selector import DecisionSelector

BASE = Path(__file__).resolve().parents[2]

class Operator(CognitiveOperator):
    def __init__(self, event_bus=None):
        self.event_bus = event_bus
        self.last_artifacts = []
        self.last_events = []

    def inputs(self):
        return ["opportunity_entity", "world_state", "objectives", "memory"]

    def validate(self, entity, session=None, **kwargs):
        if not entity:
            raise ValueError("Opportunity entity is required")
        return True

    def execute(self, entity, session=None, **kwargs):
        world_state = kwargs.get("world_state") or (session.world_state_snapshot if session else None)
        objectives = kwargs.get("objectives") or (session.objectives_snapshot if session else None)
        memory = kwargs.get("memory") or (session.memory_loaded if session else [])

        evidence_set = EvidenceRanker().run(entity, world_state, objectives, memory)
        hypotheses = HypothesisGenerator().run(entity, evidence_set)
        confidence = ConfidenceEstimator().run(evidence_set)
        selection = DecisionSelector().run(entity, confidence)

        decision_id = entity.replace("OPP", "DEC") if "OPP" in entity else f"decision_for_{entity}"
        return {
            "opportunity_id": entity,
            "decision_id": decision_id,
            "world_state": world_state,
            "objectives": objectives,
            "memory": memory,
            "evidence_set": evidence_set,
            "hypotheses": hypotheses,
            "confidence": confidence,
            "selected": selection["selected"],
            "rationale": selection["rationale"],
            "predictions": selection["predictions"],
            "session_id": getattr(session, "session_id", None),
        }

    def persist(self, result, session=None, **kwargs):
        ts = datetime.now(timezone.utc).date().isoformat()
        self.last_artifacts = []

        evidence_dir = BASE / "EVIDENCE"
        decisions_dir = BASE / "DECISIONS"
        evidence_dir.mkdir(exist_ok=True)
        decisions_dir.mkdir(exist_ok=True)

        evidence_path = evidence_dir / f"evidence_set_for_{result['decision_id']}.md"
        ev_lines = [
            f"# Evidence Set for {result['decision_id']}",
            "",
            "## Identity",
            f"- Evidence Set ID: evset-{result['decision_id']}",
            f"- Session: {result['session_id'] or 'none'}",
            f"- Source Opportunity: {result['opportunity_id']}",
            "",
            "## Evidence Items",
        ]
        for item in result['evidence_set']:
            ev_lines.extend([f"- {item['evidence_id']} | {item['source']} | weight={item['weight']:.2f} | {item['summary']}"])
        ev_lines.extend([
            "",
            "## Supporting World State",
            f"- {result['world_state'] or 'none'}",
            "",
            "## Supporting Objectives",
            f"- {result['objectives'] or 'none'}",
            "",
            "## Supporting Memory",
        ])
        if result['memory']:
            ev_lines.extend([f"- {m}" for m in result['memory']])
        else:
            ev_lines.append("- none")
        ev_lines.extend([
            "",
            "## Generated Hypotheses",
            *[f"- {h}" for h in result['hypotheses']],
            "",
            "## Confidence Estimate",
            f"- {result['confidence']:.2f}",
            "",
            "## Last Updated",
            f"- {ts}",
        ])
        evidence_path.write_text("
".join(ev_lines) + "
")
        self.last_artifacts.append(evidence_path)

        if result['selected']:
            decision_path = decisions_dir / f"{result['decision_id']}.md"
            lines = [
                f"# Decision: {result['decision_id']}",
                "",
                "## Identity",
                f"- Decision ID: {result['decision_id']}",
                f"- Originating Opportunity: {result['opportunity_id']}",
                f"- Session: {result['session_id'] or 'none'}",
                "",
                "## Canonical Basis",
                "- Generated by the Opportunity → Decision cognitive operator.",
                "",
                "## Context",
                f"- World State: {result['world_state'] or 'none'}",
                f"- Objectives: {result['objectives'] or 'none'}",
                f"- Evidence Set: {evidence_path.name}",
                "",
                "## Hypotheses",
                *[f"- {h}" for h in result['hypotheses']],
                "",
                "## Predictions",
                *[f"- {p}" for p in result['predictions']] if result['predictions'] else ["- none"],
                "",
                "## Rationale",
                result['rationale'],
                "",
                "## Links",
                f"- Opportunity: {result['opportunity_id']}",
                f"- Evidence: {evidence_path.name}",
                *[f"- Memory: {m}" for m in result['memory']],
                "",
                "## Current State",
                "Selected",
                "",
                "## Change History",
                "- Initialized by Opportunity → Decision operator.",
                "",
                "## Last Updated",
                f"- {ts}",
            ]
            decision_path.write_text("
".join(lines) + "
")
            self.last_artifacts.append(decision_path)
            return decision_path
        return evidence_path

    def emit_events(self, result, session=None, **kwargs):
        self.last_events = []
        if not self.event_bus:
            return []
        if result['selected']:
            self.last_events.append(self.event_bus.emit(
                'DecisionCreated',
                operator='OpportunityToDecision',
                source_entity=result['opportunity_id'],
                target_entity=result['decision_id'],
                payload={'confidence': result['confidence'], 'session_id': result['session_id']}
            ))
        else:
            self.last_events.append(self.event_bus.emit(
                'DecisionRejected',
                operator='OpportunityToDecision',
                source_entity=result['opportunity_id'],
                target_entity=None,
                payload={'confidence': result['confidence'], 'session_id': result['session_id']}
            ))
        return self.last_events
