from pathlib import Path
from datetime import datetime, timezone
from collections import OrderedDict
from OPERATORS.engine import CognitiveOperator
import entity_markdown as em

BASE = Path(__file__).resolve().parents[2]

MEMORY_REQUIRED_SECTIONS = ["Identity", "Learning"]

REASONING_SNAPSHOT_SECTION_ORDER = [
    "Identity",
    "Ownership",
    "Canonical Basis",
    "Source Memory",
    "Projected Hypotheses",
    "Projected Learning",
    "Projected Predictions",
    "Projected Consequences",
    "Context Notes",
    "Links",
    "Current State",
    "Change History",
    "Last Updated",
]


class NoUsableLearningError(Exception):
    pass


class Operator(CognitiveOperator):
    """
    Memory → Reasoning operator.

    Consumes a persisted Memory entity (MEMORY/*.md, produced by
    LearningToMemory) and projects its epistemic content into the active
    CognitiveSession as session.memory_loaded, making it available to
    downstream operators (principally OpportunityToDecision via
    EvidenceRanker).

    Simultaneously persists a dated reasoning-context snapshot in
    REASONING_PARAMETERS/ so that every Memory→Reasoning projection is
    traceable and auditable, per ADR-008 invariant 5
    (every authoritative epistemic state change must be traceable).

    Pipeline contract:
    - Input  : path to a Memory entity file (MEMORY/*.md)
    - Output : path to the persisted reasoning-context snapshot
               (REASONING_PARAMETERS/reasoning-context-<memory-stem>.md)
    - Side effect: session.memory_loaded is populated with projected items
                   if a session is active.
    """

    def __init__(self, event_bus=None):
        self.event_bus = event_bus
        self.last_artifacts = []
        self.last_events = []

    def inputs(self):
        return ["memory_path"]

    def validate(self, entity, session=None, **kwargs):
        if not entity:
            raise ValueError("A Memory entity path is required.")
        path = Path(entity)
        if not path.exists():
            raise ValueError(f"Memory entity path does not exist: {path}")
        sections = em.load_entity(path)
        em.validate_entity_structure(sections, MEMORY_REQUIRED_SECTIONS)
        learning_content = sections.get("Learning", "").strip()
        if not learning_content or learning_content.lower() in (
            "none inherited.",
            "none",
            "no resolved predictions to learn from yet.",
        ):
            raise NoUsableLearningError(
                f"Memory entity at {path} contains no usable Learning content "
                "and cannot seed a reasoning context."
            )
        return True

    def execute(self, entity, session=None, **kwargs):
        memory_path = Path(entity)
        sections = em.load_entity(memory_path)

        relative_memory_path = (
            memory_path.relative_to(BASE)
            if memory_path.is_absolute() and memory_path.is_relative_to(BASE)
            else memory_path
        )

        memory_identity = sections.get("Identity", memory_path.stem)
        today = datetime.now(timezone.utc).date().isoformat()

        # Extract projectable fields
        learning_raw = sections.get("Learning", "").strip()
        hypotheses_raw = sections.get("Hypotheses", "").strip()
        predictions_raw = sections.get("Predictions", "").strip()
        consequences_raw = sections.get("Consequences", "").strip()
        context_raw = sections.get("Context", "").strip()

        # Build flat list for session.memory_loaded (consumed by EvidenceRanker)
        projected_items = []
        for line in learning_raw.splitlines():
            stripped = line.strip().lstrip("- ").strip()
            if stripped:
                projected_items.append(stripped)

        # Inject into session if active
        if session is not None:
            existing = list(session.memory_loaded or [])
            merged = existing + [
                item for item in projected_items if item not in existing
            ]
            session.memory_loaded = merged

        snapshot_id = f"reasoning-context-{memory_path.stem}"

        snapshot_sections = OrderedDict()
        snapshot_sections["__title__"] = f"Reasoning Context: {memory_identity}"
        snapshot_sections["Identity"] = snapshot_id
        snapshot_sections["Ownership"] = (
            "Owned by the Memory Organ, per QENKI_MIND_ORGANS_v1.md. "
            "Generated by the Memory \u2192 Reasoning cognitive operator. "
            "Consumed read-only by downstream operators; mutable only by "
            "Learning & Reflection, per ADR-008 invariant 3."
        )
        snapshot_sections["Canonical Basis"] = str(relative_memory_path)
        snapshot_sections["Source Memory"] = memory_identity
        snapshot_sections["Projected Hypotheses"] = (
            hypotheses_raw if hypotheses_raw else "None inherited."
        )
        snapshot_sections["Projected Learning"] = (
            learning_raw if learning_raw else "None."
        )
        snapshot_sections["Projected Predictions"] = (
            predictions_raw if predictions_raw else "None inherited."
        )
        snapshot_sections["Projected Consequences"] = (
            consequences_raw if consequences_raw else "None inherited."
        )
        snapshot_sections["Context Notes"] = (
            context_raw
            if context_raw
            else "Derived automatically from Memory entity; no additional context recorded."
        )
        snapshot_sections["Links"] = em.build_bullet_section(
            [str(relative_memory_path), "REASONING_PARAMETERS/README.md"]
        )
        snapshot_sections["Current State"] = "Active"
        snapshot_sections["Change History"] = em.build_bullet_section(
            [
                f"{today}: Initialized by MemoryToReasoning operator from "
                f"{relative_memory_path}."
            ]
        )
        snapshot_sections["Last Updated"] = today

        return {
            "memory_path": memory_path,
            "memory_identity": memory_identity,
            "snapshot_id": snapshot_id,
            "snapshot_sections": snapshot_sections,
            "projected_items": projected_items,
            "session_id": getattr(session, "session_id", None),
        }

    def persist(self, result, session=None, **kwargs):
        self.last_artifacts = []
        params_dir = BASE / "REASONING_PARAMETERS"
        params_dir.mkdir(exist_ok=True)

        snapshot_path = params_dir / f"{result['snapshot_id']}.md"
        em.save_entity(
            snapshot_path,
            result["snapshot_sections"],
            section_order=REASONING_SNAPSHOT_SECTION_ORDER,
        )
        self.last_artifacts.append(snapshot_path)
        return snapshot_path

    def emit_events(self, result, session=None, **kwargs):
        self.last_events = []
        if not self.event_bus:
            return []
        event = self.event_bus.emit(
            event_type="MemoryProjected",
            operator="MemoryToReasoning",
            source_entity=str(result["memory_path"]),
            target_entity=result["snapshot_id"],
            payload={
                "projected_items_count": len(result["projected_items"]),
                "session_id": result["session_id"],
            },
        )
        self.last_events.append(event)
        return self.last_events