from pathlib import Path
from datetime import datetime, timezone
from collections import OrderedDict
from OPERATORS.engine import CognitiveOperator
import entity_markdown as em

BASE = Path(__file__).resolve().parents[2]

MINIMAL_ENTITY_STRUCTURE = [
    "Identity", "Ownership", "Canonical Basis", "Context", "Hypotheses",
    "Predictions", "Consequences", "Learning", "Links", "Current State",
    "Change History", "Last Updated"
]

INHERITED_FIELDS = ["Context", "Hypotheses", "Predictions", "Consequences", "Learning"]


class Operator(CognitiveOperator):
    """
    Transforms a persisted Decision entity into a persisted Expression
    entity. Consumes and produces artifacts (files), per the pipeline
    contract: execute() loads the Decision from disk, persist() writes
    the Expression to disk. No manual Markdown construction; all
    serialization is delegated to entity_markdown.py.
    """

    def __init__(self, event_bus=None):
        self.event_bus = event_bus
        self.last_artifacts = []
        self.last_events = []

    def inputs(self):
        return ["decision_entity_path"]

    def validate(self, entity, session=None, **kwargs):
        if not entity:
            raise ValueError("A Decision entity path is required")
        path = Path(entity)
        if not path.exists():
            raise ValueError(f"Decision entity path does not exist: {path}")
        return True

    def execute(self, entity, session=None, **kwargs):
        decision_path = Path(entity)
        decision_sections = em.load_entity(decision_path)
        em.validate_entity_structure(decision_sections, MINIMAL_ENTITY_STRUCTURE)

        relative_decision_path = decision_path.relative_to(BASE) if decision_path.is_relative_to(BASE) else decision_path
        source_identity = em.get_section(decision_sections, "Identity")
        existing_links = em.parse_bullet_list(em.get_section(decision_sections, "Links"))
        today = datetime.now(timezone.utc).date().isoformat()

        expression = OrderedDict()
        expression["__title__"] = "Expression: Derived from Decision"

        expression["Identity"] = (
            source_identity.replace("decision-", "expression-", 1)
            if "decision-" in source_identity
            else f"expression-derived-from-{source_identity}"
        )
        expression["Ownership"] = (
            "Owned by the Expression Organ, per QENKI_MIND_ORGANS_v1.md. "
            "Generated by the Decision \u2192 Expression cognitive operator."
        )
        expression["Canonical Basis"] = str(relative_decision_path)

        for field in INHERITED_FIELDS:
            expression[field] = em.get_section(decision_sections, field)

        expression_links = list(existing_links) + [str(relative_decision_path)]
        expression["Links"] = em.build_bullet_section(expression_links)
        expression["Current State"] = "Drafted"
        expression["Change History"] = em.build_bullet_section(
            [f"{today}: Initialized by DecisionToExpression operator from {relative_decision_path}."]
        )
        expression["Last Updated"] = today

        return {
            "decision_path": decision_path,
            "expression_sections": expression,
            "decision_identity": source_identity,
            "session_id": getattr(session, "session_id", None),
        }

    def persist(self, result, session=None, **kwargs):
        self.last_artifacts = []
        expressions_dir = BASE / "EXPRESSIONS"
        expressions_dir.mkdir(exist_ok=True)

        expression_sections = result["expression_sections"]
        em.validate_entity_structure(expression_sections, MINIMAL_ENTITY_STRUCTURE)

        expression_id = expression_sections["Identity"]
        expression_path = expressions_dir / f"{expression_id}.md"

        em.save_entity(expression_path, expression_sections)
        self.last_artifacts.append(expression_path)
        return expression_path

    def emit_events(self, result, session=None, **kwargs):
        self.last_events = []
        if not self.event_bus:
            return []
        event = self.event_bus.emit(
            event_type="ExpressionPublished",
            operator="DecisionToExpression",
            source_entity=str(result["decision_path"]),
            target_entity=result["expression_sections"]["Identity"],
            payload={"session_id": result["session_id"]},
        )
        self.last_events.append(event)
        return self.last_events
